FROM node:12-alpine

WORKDIR /project

COPY package*.json ./
RUN npm i

ENV EXPOSED_API_HOST=http://localhost:1337
ENV INTERNAL_API_HOST=localhost
COPY . ./
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]